server:
  port: 8081
  servlet:
    context-path: /PhoneBook
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: system
    password: Pprem@9695800
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update    
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
